version: '3'

services:
  web:
    container_name: varaamo-frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
      - '5858:5858'
      - '9229:9229'
    environment:
      - NODE_ENV='development'
